config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :tracks



  namespace :admin do
    root 'users#index'

    resources :users
    resources :tracks
    resources :sections do
      resources :assignments, controller: 'section_assignments'
      resources :quizzes, controller: 'section_quizzes'
    end
  end

  get '/guide/welcome' => 'guide#welcome'

  root to: 'guide#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :section
  has_many :quizzes

  def deadline
    if self.duedate.present?
      self.duedate.strftime('%Y-%m-%d %H:%M')
    else
      ""
    end
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :assignment
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :track

  has_many :assignments
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :users
  has_many :sections
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  belongs_to :track

  def admin?
    true if self.role == "admin"
  end

  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :check_admin
  layout "admin"

  private

  def check_admin
    redirect_to root_path, :notice =>"Oooops?!" unless current_user.admin?
  end
end

app/controllers/admin/section_assignments_controller.rb
class Admin::SectionAssignmentsController < Admin::AdminController
  before_action :set_section

  def create
    @assignment = @section.assignments.new(assignment_params)

    if @assignment.save
      redirect_to admin_section_path(@section)
      flash[:notice] = "新增作業：#{@assignment.name}"
    else
      render 'admin/sections#show'
    end
  end

  def update
    set_assignment

    if @assignment.update(assignment_params)
      redirect_to admin_section_path(@section)
      flash[:notice] = "修改成功"
    else
      render 'admin/sections#index'
    end
  end

  def destroy
    set_assignment
    @assignment.destroy

    redirect_to admin_section_path(@section)
    flash[:alert] = "刪除 #{@assignment.name}"
  end

  private
  def assignment_params
    params.require(:assignment).permit(:name, :duedate, :is_opensource)
  end

  def set_section
    @section = Section.find(params[:section_id])
  end

  def set_assignment
    @assignment = Assignment.find(params[:id])
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::AdminController
  before_action :set_section, only: [:show, :update, :destroy]

  def index
    @sections = Section.all

    if params[:id]
      set_section
    else
      @section = Section.new
    end
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to admin_sections_path
      flash[:notice] = "新增成功"
    else
      render 'admin/sections#index'
    end
  end

  def show
    @assignments = @section.assignments

    if params[:assignment]
      @assignment = @section.assignments.find(params[:assignment])
    else
      @assignment = Assignment.new(duedate: (DateTime.now + 3.days).to_date - 2.hours )
    end
  end

  def update
    if @section.update(section_params)
      redirect_to admin_sections_path
      flash[:notice] = "修改成功"
    else
      render 'admin/sections#index'
    end
  end

  def destroy
    @section.destroy
    redirect_to admin_sections_path
  end


  private

  def section_params
    params.require(:section).permit(:name)
  end

  def set_section
    @section = Section.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guide_controller.rb
class GuideController < ApplicationController
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tracks = Track.all

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/assignments_helper.rb
module Admin::AssignmentsHelper
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users/omniauth_callbacks_controller_helper.rb
module Users::OmniauthCallbacksControllerHelper
end

app/views/admin/assignments/index.html.erb
<h3>assignment index</h3>

app/views/admin/sections/index.html.erb
<h3>課程總表</h3>

<%= form_for [:admin, @track, @section] do |f| %>
  <%= f.hidden_field :track_id %>
  <%= f.label :name, "課程名稱" %>
  <%= f.text_field :name %>
  <%= f.submit class: "btn btn-primary btn-sm"  %>
<% end %>
<br>
<table class="table table-condensed table-bordered table-responsive">
  <tr>
    <th class="section_name">Section</th>
    <th>Assignment</th>
    <th>date</th>
    <th></th>
  </tr>
  <% @sections.each do |section| %>
    <tr>
      <td><%= link_to section.name, admin_section_path(section) %><br>
      </td>
      <td>
        <% section.assignments.each do |assignment| %>
          <%= assignment.name %><br>
        <% end %>
      </td>
      <td></td>
      <td><%= link_to 'edit', admin_sections_path(id: section.id) %></td>
    </tr>
  <% end %>

</table>

app/views/admin/sections/show.html.erb
<h3><%= @section.name %></h3>

<table class="table table-condensed table-hover table-responsive">
  <tr>
    <th>#</th>
    <th>Assignment</th>
    <th>Deadline</th>
    <th>open</th>
    <th></th>
  </tr>
  <% @assignments.each do |assignment| %>
    <tr>
      <td><%= assignment.id %></td>
      <td><%= assignment.name %></td>
      <td><%= assignment.deadline %></td>
      <td></td>
      <td><%= link_to '編輯', admin_section_path(assignment: assignment.id) %>｜<%= link_to'刪除', admin_section_assignment_path(@section, assignment), method: :delete %></td>
    </tr>
  <% end %>
</table>

<% if params[:assignment].present? %>
  <h4>編輯作業</h4>
<% else %>
  <h4>發佈作業</h4>
<% end %>

<%= simple_form_for [:admin, @section, @assignment], html: {class: 'form-inline' } do |f| %>
  <%= f.input :name, label: 'Assignment '  %>
  <div class="form-group">
    <%= f.label 'deadline' %>
    <%= f.datetime_field :duedate, class: 'form-control' %>
  </div>
  <%= f.button :submit, class: "btn-sm btn-primary" %>
<% end %>

app/views/admin/users/index.html.erb
<h3>成員總表</h3>
<table class="table table-bordered table-hover">
  <tr>
    <th>track</th>
    <th>Name</th>
    <th>Email</th>
    <th>Role</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= Track.find(user.track_id).name %></td>
      <td><%=user.name %></td>
      <td><%=user.email %></td>
      <td><%=user.role %></td>
    </tr>
  <% end %>
</table>

app/views/guide/index.html.erb
<h3>指南</h3>

Page needs:

<h5>前台</h5>
<ol>
  <li>登入畫面 </li>
  <li>首頁：section > assignment <%= link_to '[link]', guide_welcome_path  %></li>
  <li>點 assignment 進入 quiz 詳情，可以給 answer<br>
  -- quiz 下可看見回應，或是另有 comment 頁</li>
  <li>就特定 assignment, 全班人的答案分享</li>
  <li>完成度／profile</li>
</ol>


<h5>Admin</h5>
<ol>
  <li>users <%= link_to '[link]', admin_users_path %></li>
  <li>section CRUD</li>
  <li>assignment CRUD</li>
  <li>assignment > quiz CRUD</li>
  <li>answer 一覽</li>
  <li>就特定 assignment 改權限</li>
</ol>

app/views/guide/welcome.html.erb
welcome

app/views/tracks/index.html.erb
<%= @tracks %>