config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :tracks



  namespace :admin do
    root 'users#index'

    resources :users
    resources :tracks
    resources :sections do
      resources :assignments, controller: 'section_assignments'
      resources :quizzes, controller: 'section_quizzes'
    end
  end

  get '/guide/welcome' => 'guide#welcome'

  root to: 'guide#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :section
  has_many :quizzes

  def deadline
    if self.duedate.present?
      self.duedate.strftime('%Y-%m-%d %H:%M')
    else
      ""
    end
  end
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :assignment
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :track

  has_many :assignments
end

app/models/track.rb
class Track < ApplicationRecord
  has_many :users
  has_many :sections
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  belongs_to :track

  def admin?
    true if self.role == "admin"
  end

  def self.from_omniauth(auth)
     # Case 1: Find existing user by facebook uid
     user = User.find_by_fb_uid( auth.uid )
     if user
        user.fb_token = auth.credentials.token
        #user.fb_raw_data = auth
        user.save!
       return user
     end

     # Case 2: Find existing user by email
     existing_user = User.find_by_email( auth.info.email )
     if existing_user
       existing_user.fb_uid = auth.uid
       existing_user.fb_token = auth.credentials.token
       #existing_user.fb_raw_data = auth
       existing_user.save!
       return existing_user
     end

     # Case 3: Create new password
     user = User.new
     user.fb_uid = auth.uid
     user.fb_token = auth.credentials.token
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
     #user.fb_raw_data = auth
     user.save!
     return user
   end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :check_admin
  layout "admin"

  private

  def check_admin
    redirect_to root_path, :notice =>"Oooops?!" unless current_user.admin?
  end
end

app/controllers/admin/section_assignments_controller.rb
class Admin::SectionAssignmentsController < Admin::AdminController
  before_action :set_section

  def create
    @assignment = @section.assignments.new(assignment_params)

    if @assignment.save
      redirect_to admin_section_path(@section)
      flash[:notice] = "新增作業：#{@assignment.name}"
    else
      render 'admin/sections#show'
    end
  end

  def update
    set_assignment

    if @assignment.update(assignment_params)
      redirect_to admin_section_path(@section)
      flash[:notice] = "修改成功"
    else
      render 'admin/sections#index'
    end
  end

  def destroy
    set_assignment
    @assignment.destroy

    redirect_to admin_section_path(@section)
    flash[:alert] = "刪除 #{@assignment.name}"
  end

  private
  def assignment_params
    params.require(:assignment).permit(:name, :duedate, :is_opensource)
  end

  def set_section
    @section = Section.find(params[:section_id])
  end

  def set_assignment
    @assignment = Assignment.find(params[:id])
  end
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < Admin::AdminController
  before_action :set_section, only: [:show, :update, :destroy]

  def index
    @sections = Section.all

    if params[:id]
      set_section
    else
      @section = Section.new
    end
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      redirect_to admin_sections_path
      flash[:notice] = "新增成功"
    else
      render 'admin/sections#index'
    end
  end

  def show
    @assignments = @section.assignments

    if params[:assignment]
      @assignment = @section.assignments.find(params[:assignment])
    else
      @assignment = Assignment.new(duedate: (DateTime.now + 3.days).to_date - 2.hours )
    end
  end

  def update
    if @section.update(section_params)
      redirect_to admin_sections_path
      flash[:notice] = "修改成功"
    else
      render 'admin/sections#index'
    end
  end

  def destroy
    @section.destroy
    redirect_to admin_sections_path
  end


  private

  def section_params
    params.require(:section).permit(:name)
  end

  def set_section
    @section = Section.find(params[:id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guide_controller.rb
class GuideController < ApplicationController
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!

  def index
    @tracks = Track.all

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/assignments_helper.rb
module Admin::AssignmentsHelper
end

app/helpers/admin/sections_helper.rb
module Admin::SectionsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JevApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="clearfix">
      <ul class="list-inline pull-left">
        <li><%= link_to '成員總表', admin_users_path %></li>
        <li><%= link_to '課程總表', admin_sections_path %></li>
        <li><%= link_to '作業總表' %></li>
        <li><%= link_to '題目總表' %></li>

      </ul>
      <div class="pull-right">
        <% if current_user %>
          (<%= current_user.email %>)
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
        <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %>
        <% end %>

      </div>
    </nav>

    <!-- 警告訊息 -->
    <% if flash[:notice].present? %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice]%>
      </div>
    <% elsif flash[:alert].present? %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert]%>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JevApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to 'index', root_path %> |
      <%= link_to 'admin', admin_users_path %> |
      (<%= current_user.email %>)
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
      <%= link_to('修改密碼', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
      <%= link_to('登入', new_session_path(:user)) %> |
      <%= link_to "登入 Facebook", user_facebook_omniauth_authorize_path %>
    <% end %>

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>